### ISSUE TITLE
启动后显示'AntDesign' was undefined且无法登入

### ISSUE THREAD

**Issue by tzengshinfu** [AIDotNet/AntSK#104]
作业系统 Windows 10及Ubuntu 20.04
已预装.NET SDK 8.0.401
已预装.NET Aspire SDK
已依[⚠️Fixing Style Issues](https://github.com/AIDotNet/AntSK?tab=readme-ov-file#%EF%B8%8Ffixing-style-issues)步骤执行

问题重现
1. 创建目录`D:\Workspace`
2. 执行`git clone https://github.com/AIDotNet/AntSK.git`
3. 创建目录`D:\model`及`D:\model\logs`
4. 变更工作目录`D:\Workspace\AntSK\src\AntSK`
5. 执行`dotnet clean` 无错误讯息
6. 执行`dotnet build` 无错误讯息
7. 执行`dotnet publish "AntSK.csproj"` 无错误讯息
8. 执行`dotnet bin\Release\net8.0\publish\AntSK.dll` 主控台显示
```
[14:19:13 INF] 初始化表结构完成
[14:19:13 INF] 初始化数据库初始数据完成
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Workspace\AntSK\src\AntSK
```
9. 开启首页`http://127.0.0.1:5000/api`
10. 首页显示不正确如下图
![image_20240829_142440](https://github.com/user-attachments/assets/0bad2fe5-7ff8-46eb-95ee-21503198df12)
11. 主控台显示错误讯息且无法登入
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Alert.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'fRG7Kymq747H_5m_BUUJc7sAl19TDKh0ZuAhQOPRnNg'.
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getInfo' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Alert.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Sider.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'fRG7Kymq747H_5m_BUUJc7sAl19TDKh0ZuAhQOPRnNg'.
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Sider.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Select`2.SetDropdownStyleAsync()
         at AntDesign.Select`2.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'fRG7Kymq747H_5m_BUUJc7sAl19TDKh0ZuAhQOPRnNg'.
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getBoundingClientRect' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
         at AntDesign.Select`2.SetDropdownStyleAsync()
         at AntDesign.Select`2.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at AntDesign.Internal.OverlayTrigger.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'fRG7Kymq747H_5m_BUUJc7sAl19TDKh0ZuAhQOPRnNg'.
      Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
Error: Could not find 'AntDesign.interop.styleHelper.addCls' ('AntDesign' was undefined).
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://127.0.0.1:5000/_framework/blazor.server.js:1:505)
    at _ (http://127.0.0.1:5000/_framework/blazor.server.js:1:5248)
    at http://127.0.0.1:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://127.0.0.1:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://127.0.0.1:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://127.0.0.1:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://127.0.0.1:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at AntDesign.Internal.OverlayTrigger.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by xuzeyu91** [comment]
样式没有正确生成，Windows可以使用Visual studio 2022启动 。linux可以直接使用docker-compose
