### ISSUE TITLE
使用PG向量库，知识库导入文本报错 dimensions for type vector must be at least 1

### ISSUE THREAD

**Issue by yc-2503** [AIDotNet/AntSK#68]
Microsoft.KernelMemory.Postgres.PostgresMemory[0]
      Table 'public."km-kms"' creation error: Npgsql.PostgresException (0x80004005): 22023: dimensions for type vector must be at least 1

      POSITION: 141
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.CreateTableAsync(String tableName, Int32 vectorSize, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.CreateTableAsync(String tableName, Int32 vectorSize, CancellationToken cancellationToken)
        Exception data:
          Severity: ERROR
          SqlState: 22023
          MessageText: dimensions for type vector must be at least 1
          Position: 141
          File: vector.c
          Line: 356
          Routine: vector_typmod_in. Err: 22023: dimensions for type vector must be at least 1

      POSITION: 141. InnerEx: (null)
      Npgsql.PostgresException (0x80004005): 22023: dimensions for type vector must be at least 1

      POSITION: 141
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.CreateTableAsync(String tableName, Int32 vectorSize, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.CreateTableAsync(String tableName, Int32 vectorSize, CancellationToken cancellationToken)
        Exception data:
          Severity: ERROR
          SqlState: 22023
          MessageText: dimensions for type vector must be at least 1
          Position: 141
          File: vector.c
          Line: 356
          Routine: vector_typmod_in

**Comment by xuzeyu91** [comment]
看起来是你的向量模型配置有问题
